### ISSUE TITLE
[Windows 10][Vivaldi] Buttons have strange borders

### ISSUE THREAD

**Issue by Gioni06** [Gioni06/terminal.css#12]
On Windows 10 with Vivaldi (Chrome) Browser buttons have strange borders.

![buttons](https://user-images.githubusercontent.com/536849/51935487-51a9d880-2406-11e9-8cbc-9eb52890df98.PNG)

**Comment by matiaskorhonen** [comment]
The same is true on Safari:

<img width="682" alt="Screenshot of the buttons on Safari" src="https://user-images.githubusercontent.com/43314/53401446-7dde5800-39b8-11e9-9bd3-0683518613f6.png">
