### ISSUE TITLE
Dark mode shows multiple lines for CDN

### ISSUE THREAD

**Issue by daxm** [Gioni06/terminal.css#27]
Probably just a typo but your website https://terminalcss.xyz/dark/ shows multiple lines for the CDN link whereas the other pages just show 1 link.

**Comment by marcuxyz** [comment]
I think that was left there by accident. I can climb a `pr`

**Comment by Gioni06** [comment]
@marcuxyz Good catch! Sorry, this got lost between all the Github notifications.
