### ISSUE TITLE
Site documentation

### ISSUE THREAD

**Issue by eddyizm** [Gioni06/terminal.css#42]
is the [terminalcss.xyz](https://terminalcss.xyz/) site open source? I'd like to help contribute to it as I start to use this.

**Comment by Gioni06** [comment]
> is the [terminalcss.xyz](https://terminalcss.xyz/) site open source? I'd like to help contribute to it as I start to use this.

Sure, it's a very primitive approach to building it as a static site. What are your plans?

**Comment by eddyizm** [comment]
I was going to start by adding the html examples in code blocks instead of having to look in the source code or inspector.
