### ISSUE TITLE
images mistake

### ISSUE THREAD

**Issue by diomed** [Gioni06/terminal.css#43]
you put 

```
img {
  width: 100%;
}

```

when it's supposed to be 

```
img {
  max-width: 100%;
}
```

this causes all images to be very big , unlike with other css [minimal] frameworks.

**Comment by Gioni06** [comment]
That is a valid point. When we change it, it might break peoples layouts though. I'm not sure how to proceed.

**Comment by diomed** [comment]
how does it break layouts?

i suggest changing it.

**Comment by Gioni06** [comment]
fixed https://github.com/Gioni06/terminal.css/commit/308e015f3d6f44bc819ebbd1a541657fbe770a80

Thanks!!
