### ISSUE TITLE
.terminal-nav can cause problems

### ISSUE THREAD

**Issue by marcuxyz** [Gioni06/terminal.css#44]
### Context
The navbar was broken when adding flex to the body element.

### Problem
when adding flex property to the body element to the fixed footer in the bottom, the navbar is broken.

<img width="1748" alt="Captura de Tela 2023-09-19 às 13 37 02" src="https://github.com/Gioni06/terminal.css/assets/9499562/d5cc3c97-8f7e-4638-a3b9-f9e1f27d3331">

### Solution

add `gap: 100vh` to create space between elements.

<img width="996" alt="Captura de Tela 2023-09-19 às 13 43 23" src="https://github.com/Gioni06/terminal.css/assets/9499562/0d474c6d-a9e5-4684-ad45-929ebc30051b">

**Comment by Gioni06** [comment]
<img width="1726" alt="CleanShot 2023-09-19 at 19 57 51@2x" src="https://github.com/Gioni06/terminal.css/assets/536849/04aa544b-ebc5-4159-834b-23e2946285ce">
